version: '3'
services:
  postgres:
    container_name: api_exemple_db
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_exemple
  rabbitmq:
    hostname: rabbitmq
    container_name: "rabbitmq"
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
