server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api-exemple/v1
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "info,health"
spring:
  jpa:
    database: postgresql
    show-sql: ${HIBERNATE_SHOW_SQL:true}
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
    open-in-view: false
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/api_exemple}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:20}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:2}
  main:
    allow-bean-definition-overriding: true

rest:
  api:
    cep: ${HOST_CEP:https://api.postmon.com.br/v1}
